[docs] add Q&A: undefined reference to 'cbrt' (#2)
The cbrt function is part of the math library (libm), which needs to be explicitly linked.
Resolve discussions #370.